name: data4cv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - opencv
  - pycocotools
  - pytest
  - ruff
  - pip:
      - -e .
